config/routes.rb
::Refinery::Application.routes.draw do
  resources :carts, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :carts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :line_items, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :line_items, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  before_save :check_is_current_for_sibling_carts
  
  belongs_to :customer
  has_many :line_items
  has_many :products, :through => :line_items
  
  # def title was created automatically because you didn't specify a string field
  # when you ran the refinery_engine generator. Love, Refinery CMS.
  def title
    "Override def title in vendor/engines/carts/app/models/cart.rb"
  end
  
  def grand_total
    total = 0
    line_items.each do |li|
      total += li.total_price
    end
    total
  end
  
  
  def add_to_the_cart(product_id, quantity = 1, variant_id = nil)
    if variant_id.blank?
      li = self.line_items.where(:product_id => product_id).first
    else
      li = self.line_items.where(:product_id => product_id, :variant_id => variant_id).first
    end  
    
    #logger.info("****************** the variant id = #{variant_id}")
    
    if li.present?
      li.quantity += quantity.to_i
      li.save
    else
      if variant_id.blank?  
        self.line_items.create(:product_id => product_id, :quantity => quantity)
      else
        self.line_items.create(:product_id => product_id, :quantity => quantity, :variant_id => variant_id)
      end
      
    end 
  end
  
  def check_is_current_for_sibling_carts
    if is_current.present? and is_current == true and customer_id.present?
      other_carts = Cart.where(:customer_id => self.customer_id)
      other_carts.each do |cart|
        cart.update_attributes(:is_current => false) if cart.id != self.id
      end
    end
  end
  
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :cart
  belongs_to :product
  belongs_to :variant
  
  # def title was created automatically because you didn't specify a string field
  # when you ran the refinery_engine generator. Love, Refinery CMS.
  def title
    "Override def title in vendor/engines/line_items/app/models/line_item.rb"
  end
  
  def total_price
    if variant_id.blank?  
      product.price * quantity
    else
      variant.price * quantity
    end  
      
  end
  
  def grand_total
    total = 0
    line_items.each do |li|
      total += li.total_price
    end
    total
  end
  
end

app/controllers/admin/carts_controller.rb
module Admin
  class CartsController < Admin::BaseController

    crudify :cart, :xhr_paging => true

  end
end

app/controllers/admin/line_items_controller.rb
module Admin
  class LineItemsController < Admin::BaseController

    crudify :line_item, :xhr_paging => true

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add_to_cart
      check_quantity_then_update_cart  
      
      
      # logger.info("****************** the variant = #{params[:variant][:id]}")
      
      
      redirect_to_products("Product added to Cart")
        
  end
  
  def show_cart
    
  end
  
  def check_quantity_then_update_cart 

    #logger.info("****************** the variant = #{params[:variant][:id]}")
  
    if params[:quantity].present?
      if params[:variant].present?
        @current_cart.add_to_the_cart(params[:product_id], params[:quantity], params[:variant][:id])
      else
        @current_cart.add_to_the_cart(params[:product_id], params[:quantity])
      end    
    else
      if params[:variant].present?
        @current_cart.add_to_the_cart(params[:product_id], 1, params[:variant][:id])
      else
        @current_cart.add_to_the_cart(params[:product_id])
      end
    end
    
  end
    
  def increment_cart
    check_quantity_then_update_cart
    
    redirect_to show_cart_path
  end
    
  private
  
  def redirect_to_products(msg)
      flash[:notice] = msg
      
      
      if params[:category_id].present?
        if params[:category_id] == "0"
          redirect_to "/"
        else
          redirect_to category_products_path(params[:category_id])
        end    
      else
        redirect_to product_path(params[:product_id])
      end          
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  def destroy
      LineItem.destroy(params[:id])
      redirect_to show_cart_path
  end

end

app/views/admin/carts/_actions.html.erb
<ul>
  <% if Admin::CartsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_carts_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_cart_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::CartsController.sortable? and Cart.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Carts"),
                 admin_carts_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Carts"),
                 admin_carts_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/carts/_cart.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(cart) -%>">
  <span class='title'>
    <%= cart.title %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), cart_path(cart),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_cart_path(cart),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_cart_path(cart),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => cart.title),
        :method => :delete %>
  </span>
</li>

app/views/admin/carts/_carts.html.erb
<%= will_paginate @carts %>
<%= render :partial => "sortable_list" %>

app/views/admin/carts/_form.html.erb
<%= form_for [:admin, @cart] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @cart,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :customer -%>
    <%= f.text_field :customer, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :is_current -%>
    <%= f.check_box :is_current, :checked => @cart[:is_current]  -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.carts.cart'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete')
              } %>
<% end -%>

app/views/admin/carts/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @carts.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'carts' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/carts/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'cart', :collection => @carts %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/carts/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/carts/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::CartsController.sortable? and Cart.count > 1 %>

app/views/admin/carts/new.html.erb
<%= render :partial => "form" %>

app/views/admin/line_items/_actions.html.erb
<ul>
  <% if Admin::LineItemsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_line_items_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_line_item_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::LineItemsController.sortable? and LineItem.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Line Items"),
                 admin_line_items_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Line Items"),
                 admin_line_items_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/line_items/_form.html.erb
<%= form_for [:admin, @line_item] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @line_item,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :cart -%>
    <%= f.text_field :cart, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :product -%>
    <%= f.text_field :product  -%>
  </div>
  
  <div class='field'>
    <%= f.label :quantity -%>
    <%= f.text_field :quantity  -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.line_items.line_item'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete')
              } %>
<% end -%>

app/views/admin/line_items/_line_item.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(line_item) -%>">
  <span class='title'>
    <%= line_item.title %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), line_item_path(line_item),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_line_item_path(line_item),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_line_item_path(line_item),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => line_item.title),
        :method => :delete %>
  </span>
</li>

app/views/admin/line_items/_line_items.html.erb
<%= will_paginate @line_items %>
<%= render :partial => "sortable_list" %>

app/views/admin/line_items/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @line_items.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'line_items' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/line_items/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'line_item', :collection => @line_items %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/line_items/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/line_items/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::LineItemsController.sortable? and LineItem.count > 1 %>

app/views/admin/line_items/new.html.erb
<%= render :partial => "form" %>

app/views/carts/show_cart.html.erb
<% content_for :body_content_left do %>
	<%= render :partial => "/shared/cart" %>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/line_items/index.html.erb
<% content_for :body_content_left do %>
  <ul id="line_items">
    <% @line_items.each do |line_item| %>
      <li>
        <%= link_to line_item, line_item_path(line_item) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/line_items/show.html.erb
<% content_for :body_content_title do %>
  <%= @line_item.title %>
<% end %>

<% content_for :body_content_left do %>
  <section>
    <h1>Cart</h1>
    <p>
      <%=raw @line_item.cart %>
    </p>
  </section>
  <section>
    <h1>Product</h1>
    <p>
      <%=raw @line_item.product %>
    </p>
  </section>
  <section>
    <h1>Quantity</h1>
    <p>
      <%=raw @line_item.quantity %>
    </p>
  </section>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <ul id="line_items">
      <% @line_items.each do |line_item| %>
        <li>
          <%= link_to line_item.title, line_item_path(line_item) %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>

<%= render :partial => "/shared/content_page" %>